#ifndef CBRUSH_STYLE_H
#define CBRUSH_STYLE_H

enum CBrushStyle {
  CBRUSH_STYLE_NONE=0,
  CBRUSH_STYLE_SOLID=1,
  CBRUSH_STYLE_PATTERN=2,
  CBRUSH_STYLE_GRADIENT=3,
  CBRUSH_STYLE_TEXTURE=4
};

#endif
