#!/bin/csh -f

set files = ()
set gui  = 0
set diff = 0
@   tol  = 0

while ($#argv > 0)
  if      ("$1" == "-gui") then
    set gui = 1
    shift
  else if ("$1" == "-diff") then
    set diff = 1
    shift
  else if ("$1" == "-tol") then
    shift
    if ($#argv > 0) then
      @ tol = $1
      shift
    endif
  else
    set files = ($files $1)
    shift
  endif
end

if (! -e .png) then
  mkdir .png
endif

if (! -e .png_flat) then
  mkdir .png_flat
endif

if ($#files) then
  foreach file ($files)
    echo -n "Processing $file : "

    CSVGTest -flat $file >! .png_flat/$file

    set png_file = svg_${file:r}.png

    CQSVG -image -image_dir ".png" $file
    CQSVG -image -image_dir ".png_flat" .png_flat/$file

    if ($gui == 1) then
      if ($diff == 1) then
        set rc = 0

        set d = `CImageDiff .png/$png_file .png_flat/$png_file`

        if ($status == 0) then
          set rc = `echo "$d > $tol" | bc`
        else
          set rc = 1
        endif

        if ($rc) then
          echo "Different (Diff: $d, Status: $status)"

          CQImageDiff .png/$png_file .png_flat/$png_file -bg "#ffffff"
        else
          echo "Identical"
        endif
      else
        echo ""

        CQImageDiff .png/$png_file .png_flat/$png_file -bg "#ffffff"
      endif
    else
      set rc = 0

      set d = `CImageDiff .png/$png_file .png_flat/$png_file`

      if ($status == 0) then
        set rc = `echo "$d > $tol" | bc`
      else
        set rc = 1
      endif

      if ($rc) then
        echo "Different (Diff: $d, Status: $status)"
      else
        echo "Identical"
      endif
    endif
  end
else
  foreach file (fig*.svg)
    echo -n "Processing $file : "

    CSVGTest -flat $file >! .png_flat/$file

    set png_file = svg_${file:r}.png

    CQSVG -image -image_dir ".png" $file
    CQSVG -image -image_dir ".png_flat" .png_flat/$file
  
    if ($gui == 1) then
      if ($diff == 1) then
        set rc = 0

        set d = `CImageDiff .png/$png_file .png_flat/$png_file`

        if ($status == 0) then
          set rc = `echo "$d > $tol" | bc`
        else
          set rc = 1
        endif

        if ($rc) then
          echo "Different (Diff: $d, Status: $status)"

          CQImageDiff .png/$png_file .png_flat/$png_file -bg "#ffffff"
        else
          echo "Identical"
        endif
      else
        echo ""

        CQImageDiff .png/$png_file .png_flat/$png_file -bg "#ffffff"
      endif
    else
      set rc = 0

      set d = `CImageDiff .png/$png_file .png_flat/$png_file`

      if ($status == 0) then
        set rc = `echo "$d > $tol" | bc`
      else
        set rc = 1
      endif

      if ($rc) then
        echo "Different (Diff: $d, Status: $status)"
      else
        echo "Identical"
      endif
    endif
  end
endif

exit 0
